# Project information
site_name: Order button demo
site_url: https://ouxt-polaris.github.io/mkdocs_order_button/
site_author: Masaya Kataoka
site_description: ''
copyright: Copyright &copy; 2021 - OUXT Polaris

# Repository
repo_name: OUXT-Polaris/mkdocs_order_button
repo_url: https://github.com/OUXT-Polaris/mkdocs_order_button
edit_uri: ''
docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    #- header.autohide
  palette:
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github

# Plugins
plugins:
  - akizukidenshi_order_button
  # - order-button
  - search
  
# Extensions
markdown_extensions:
  - pymdownx.snippets
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - admonition

nav:
  - Home: index.md
