name: Demo

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  build_demo:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync 

      - name: Run tests
        run: uv run mkdocs build

      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'pull_request'}}
        with:
          name: site
          path: site

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name != 'pull_request'}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
